### ISSUE TITLE
binaries

### ISSUE THREAD

**Issue by deadbaed** [pierremtb/papyros-calculator#2]
maybe you could move the binaries into a release, because when you clone the repo, you clone the binaries, and it takes some time :cry:

**Comment by pierremtb** [comment]
Yeah I'll do it ASAP, thank you (sorry)

**Comment by pierremtb** [comment]
Here you go : https://github.com/papyros/calculator-app/releases/

**Comment by deadbaed** [comment]
@pierremtb merci :)
